// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: ping-pong/exclamation-service/exclamation.proto

package exclamation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExclamationService_GetExclamation_FullMethodName = "/exclamation.ExclamationService/GetExclamation"
)

// ExclamationServiceClient is the client API for ExclamationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExclamationServiceClient interface {
	GetExclamation(ctx context.Context, in *ExclamationRequest, opts ...grpc.CallOption) (*ExclamationResponse, error)
}

type exclamationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExclamationServiceClient(cc grpc.ClientConnInterface) ExclamationServiceClient {
	return &exclamationServiceClient{cc}
}

func (c *exclamationServiceClient) GetExclamation(ctx context.Context, in *ExclamationRequest, opts ...grpc.CallOption) (*ExclamationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExclamationResponse)
	err := c.cc.Invoke(ctx, ExclamationService_GetExclamation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExclamationServiceServer is the server API for ExclamationService service.
// All implementations must embed UnimplementedExclamationServiceServer
// for forward compatibility.
type ExclamationServiceServer interface {
	GetExclamation(context.Context, *ExclamationRequest) (*ExclamationResponse, error)
	mustEmbedUnimplementedExclamationServiceServer()
}

// UnimplementedExclamationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExclamationServiceServer struct{}

func (UnimplementedExclamationServiceServer) GetExclamation(context.Context, *ExclamationRequest) (*ExclamationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExclamation not implemented")
}
func (UnimplementedExclamationServiceServer) mustEmbedUnimplementedExclamationServiceServer() {}
func (UnimplementedExclamationServiceServer) testEmbeddedByValue()                            {}

// UnsafeExclamationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExclamationServiceServer will
// result in compilation errors.
type UnsafeExclamationServiceServer interface {
	mustEmbedUnimplementedExclamationServiceServer()
}

func RegisterExclamationServiceServer(s grpc.ServiceRegistrar, srv ExclamationServiceServer) {
	// If the following call pancis, it indicates UnimplementedExclamationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExclamationService_ServiceDesc, srv)
}

func _ExclamationService_GetExclamation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExclamationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExclamationServiceServer).GetExclamation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExclamationService_GetExclamation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExclamationServiceServer).GetExclamation(ctx, req.(*ExclamationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExclamationService_ServiceDesc is the grpc.ServiceDesc for ExclamationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExclamationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exclamation.ExclamationService",
	HandlerType: (*ExclamationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExclamation",
			Handler:    _ExclamationService_GetExclamation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping-pong/exclamation-service/exclamation.proto",
}
